name: infrastructure with github actions

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name : Checkout
        uses : actions/checkout@v5.0.0

      - name : SetUp JDK
        uses : actions/setup-java@v5.0.0
        with:
          java-version : '21'
          distribution: 'temurin'

      - name : Grant Permission
        run : chmod +x ./gradlew

      - name : build with gradle
        run: ./gradlew bootJar -x test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_ID }}/bon:latest



            
            
            