name: "CI/CD For GitOps"

on:
  push:
    branches: [main]

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      working-directory: ./Terraform
      TF_VAR_db_pw: ${{ secrets.DB_PW }}
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_username: ${{ secrets.DB_USERNAME }}    
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.7
    
    - name: Terraform Init
      run: terraform init -upgrade
      working-directory: ./Terraform
    
    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true
      working-directory: ./Terraform
  
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      continue-on-error: true
      working-directory: ./Terraform
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -no-color
      working-directory: ./Terraform
    
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: ./Terraform

  ansible:
    name: ansible
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible
      
      - name: Set up SSH
        working-directory: ./Ansible      
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > terra_myce_keypair.pem
          chmod 600 terra_myce_keypair.pem
      
      - name: Download Inventory File From S3 Bucket
        working-directory: ./Ansible
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: download
          bucket: bon-artifact-bucket
          source: hosts.ini 
          destination: ./inventory/hosts.ini 

      - name: Set up Backend .Env
        working-directory: ./Ansible/templates      
        run: |
          echo "${{ secrets.BACKEND_ENV }}" > .env
          cat ".env"       

      - name: Run Nat-Infra Playbook
        working-directory: ./Ansible 
        run: |
          cat "inventory/hosts.ini"
          ansible-playbook -i inventory/hosts.ini \
          playbooks/nat-infra.yml
      
      - name: Run Ansible Playbook1
        working-directory: ./Ansible 
        run: |
          ansible-playbook -i inventory/hosts.ini \
          playbooks/nginx-infra.yml  

      - name: Run Ansible Playbook2
        working-directory: ./Ansible 
        run: |
          ansible-playbook -i inventory/hosts.ini \
          playbooks/docker-infra.yml 

      - name: Run Ansible Playbook3
        working-directory: ./Ansible 
        run: |
          ansible-playbook -i inventory/hosts.ini \
          playbooks/deploy.yml 
